### ISSUE TITLE
Getting the code to work

### ISSUE THREAD

**Issue by prp-e** [shenasa-ai/persian-tts#1]
Greetings. 

Recently I was working on a [voice assistant](https://github.com/prp-e/jarvis) and I was thinking about this baby to talk in Farsi. I found your repository, but unfortunately, I haven't found any useful guides on how to use your codes. It'd be cool if you add some guides on how to get this to work. 

Regards.

**Comment by de-mh** [comment]
Hi there
unfortunately this repo is still a work in progress and its not ready to be used in production. however there is a few tips I can give to help you build your own tts.
first, if you don't need a great and human-like quality, you can start your work with [espeak](https://github.com/espeak-ng/espeak-ng). its simple and understandable but the voice quality isn't that good.
If you are looking for a really good persian tts you should start building one yourself and the first thing you need for that is voice and text dataset. [LJSpeech](https://keithito.com/LJ-Speech-Dataset/) is a great example of how your dataset should look like. 
after you have the dataset, you can start training your tts using [this repo](https://github.com/TensorSpeech/TensorFlowTTS) or [this one](https://github.com/keithito/tacotron)
